### ISSUE TITLE
A change for text size

### ISSUE THREAD

**Issue by Cha0sBEpic** [Boggartmob/OBS_Twitch_chat_CSS#3]
If you change the test size format from (3cm) to 1-32px ie (14px) in the CCS it will allow the user to adjust the size to their liking better. It took a sec to realize why the chat text was so big then adjusted it to use pixels and it works a lot better.

side not Thanks for this. Helped out a lot.

**Comment by Boggartmob** [comment]
Thanks for notice!

**Comment by Boggartmob** [comment]
@Cha0sBEpic font size is adjustable now.
